// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmexvsgslagkhjuyzats.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptZXh2c2dzbGFna2hqdXl6YXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NDE3NTIsImV4cCI6MjA3NTMxNzc1Mn0.LMo025NuqDtDkuVDUh62m59OYaUNHPnn8J1FlNe5XpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});